In [1]:
import pandas as pd
import numpy as np


In [2]:

df=pd.read_csv(r'C:\Users\Hrushikesh\OneDrive\Desktop\Data Science course\Projects\ML Project\Data\3IINFOTECH.NS.csv')

In [3]:

df

Date       Open       High        Low      Close  Adj Close  \
0     2005-04-22  59.000000  59.000000  48.000000  49.049999  41.943699   
1     2005-04-25  49.450001  49.849998  47.099998  47.480000  40.601158   
2     2005-04-26  47.830002  48.130001  46.549999  46.700001  39.934162   
3     2005-04-27  46.700001  50.880001  46.180000  48.049999  41.088573   
4     2005-04-28  48.000000  49.349998  47.330002  47.779999  40.857697   
...          ...        ...        ...        ...        ...        ...   
3712  2020-06-01   1.650000   1.650000   1.600000   1.650000   1.650000   
3713  2020-06-02   1.700000   1.700000   1.650000   1.700000   1.700000   
3714  2020-06-03   1.750000   1.750000   1.650000   1.750000   1.750000   
3715  2020-06-04   1.750000   1.800000   1.700000   1.800000   1.800000   
3716  2020-06-05   1.850000   1.950000   1.850000   1.950000   1.950000   

        Volume  
0     33041772  
1     10215112  
2      6801556  
3     18723616  
4      7412076  
...        ...  
3712   2000865  
3713   5358362  
3714   6215851  
3715   4622105  
3716   2019819  

[3717 rows x 7 columns]

In [4]:
new_df=df.copy()
new_df['Date']=pd.to_datetime(new_df['Date'])

In [5]:
new_df

Date       Open       High        Low      Close  Adj Close  \
0    2005-04-22  59.000000  59.000000  48.000000  49.049999  41.943699   
1    2005-04-25  49.450001  49.849998  47.099998  47.480000  40.601158   
2    2005-04-26  47.830002  48.130001  46.549999  46.700001  39.934162   
3    2005-04-27  46.700001  50.880001  46.180000  48.049999  41.088573   
4    2005-04-28  48.000000  49.349998  47.330002  47.779999  40.857697   
...         ...        ...        ...        ...        ...        ...   
3712 2020-06-01   1.650000   1.650000   1.600000   1.650000   1.650000   
3713 2020-06-02   1.700000   1.700000   1.650000   1.700000   1.700000   
3714 2020-06-03   1.750000   1.750000   1.650000   1.750000   1.750000   
3715 2020-06-04   1.750000   1.800000   1.700000   1.800000   1.800000   
3716 2020-06-05   1.850000   1.950000   1.850000   1.950000   1.950000   

        Volume  
0     33041772  
1     10215112  
2      6801556  
3     18723616  
4      7412076  
...        ...  
3712   2000865  
3713   5358362  
3714   6215851  
3715   4622105  
3716   2019819  

[3717 rows x 7 columns]

In [6]:


# Extract year, month, and day as separate features (optional)
new_df['Year'] = new_df['Date'].dt.year
new_df['Month'] = new_df['Date'].dt.month
new_df['Day'] = new_df['Date'].dt.day




In [7]:
new_df

Date       Open       High        Low      Close  Adj Close  \
0    2005-04-22  59.000000  59.000000  48.000000  49.049999  41.943699   
1    2005-04-25  49.450001  49.849998  47.099998  47.480000  40.601158   
2    2005-04-26  47.830002  48.130001  46.549999  46.700001  39.934162   
3    2005-04-27  46.700001  50.880001  46.180000  48.049999  41.088573   
4    2005-04-28  48.000000  49.349998  47.330002  47.779999  40.857697   
...         ...        ...        ...        ...        ...        ...   
3712 2020-06-01   1.650000   1.650000   1.600000   1.650000   1.650000   
3713 2020-06-02   1.700000   1.700000   1.650000   1.700000   1.700000   
3714 2020-06-03   1.750000   1.750000   1.650000   1.750000   1.750000   
3715 2020-06-04   1.750000   1.800000   1.700000   1.800000   1.800000   
3716 2020-06-05   1.850000   1.950000   1.850000   1.950000   1.950000   

        Volume  Year  Month  Day  
0     33041772  2005      4   22  
1     10215112  2005      4   25  
2      6801556  2005      4   26  
3     18723616  2005      4   27  
4      7412076  2005      4   28  
...        ...   ...    ...  ...  
3712   2000865  2020      6    1  
3713   5358362  2020      6    2  
3714   6215851  2020      6    3  
3715   4622105  2020      6    4  
3716   2019819  2020      6    5  

[3717 rows x 10 columns]

In [8]:
dropped_col_df=new_df.copy()
dropped_col_df=dropped_col_df.drop(columns='Date')
dropped_col_df


Open       High        Low      Close  Adj Close    Volume  Year  \
0     59.000000  59.000000  48.000000  49.049999  41.943699  33041772  2005   
1     49.450001  49.849998  47.099998  47.480000  40.601158  10215112  2005   
2     47.830002  48.130001  46.549999  46.700001  39.934162   6801556  2005   
3     46.700001  50.880001  46.180000  48.049999  41.088573  18723616  2005   
4     48.000000  49.349998  47.330002  47.779999  40.857697   7412076  2005   
...         ...        ...        ...        ...        ...       ...   ...   
3712   1.650000   1.650000   1.600000   1.650000   1.650000   2000865  2020   
3713   1.700000   1.700000   1.650000   1.700000   1.700000   5358362  2020   
3714   1.750000   1.750000   1.650000   1.750000   1.750000   6215851  2020   
3715   1.750000   1.800000   1.700000   1.800000   1.800000   4622105  2020   
3716   1.850000   1.950000   1.850000   1.950000   1.950000   2019819  2020   

      Month  Day  
0         4   22  
1         4   25  
2         4   26  
3         4   27  
4         4   28  
...     ...  ...  
3712      6    1  
3713      6    2  
3714      6    3  
3715      6    4  
3716      6    5  

[3717 rows x 9 columns]

In [9]:
dropped_col_df.columns.values

array(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'Year',
       'Month', 'Day'], dtype=object)

In [10]:
cols=['Year','Month', 'Day','Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']

dropped_col_df=dropped_col_df[cols]
dropped_col_df

Year  Month  Day       Open       High        Low      Close  Adj Close  \
0     2005      4   22  59.000000  59.000000  48.000000  49.049999  41.943699   
1     2005      4   25  49.450001  49.849998  47.099998  47.480000  40.601158   
2     2005      4   26  47.830002  48.130001  46.549999  46.700001  39.934162   
3     2005      4   27  46.700001  50.880001  46.180000  48.049999  41.088573   
4     2005      4   28  48.000000  49.349998  47.330002  47.779999  40.857697   
...    ...    ...  ...        ...        ...        ...        ...        ...   
3712  2020      6    1   1.650000   1.650000   1.600000   1.650000   1.650000   
3713  2020      6    2   1.700000   1.700000   1.650000   1.700000   1.700000   
3714  2020      6    3   1.750000   1.750000   1.650000   1.750000   1.750000   
3715  2020      6    4   1.750000   1.800000   1.700000   1.800000   1.800000   
3716  2020      6    5   1.850000   1.950000   1.850000   1.950000   1.950000   

        Volume  
0     33041772  
1     10215112  
2      6801556  
3     18723616  
4      7412076  
...        ...  
3712   2000865  
3713   5358362  
3714   6215851  
3715   4622105  
3716   2019819  

[3717 rows x 9 columns]

In [11]:
scaled_data=dropped_col_df.copy()
scaled_data

Year  Month  Day       Open       High        Low      Close  Adj Close  \
0     2005      4   22  59.000000  59.000000  48.000000  49.049999  41.943699   
1     2005      4   25  49.450001  49.849998  47.099998  47.480000  40.601158   
2     2005      4   26  47.830002  48.130001  46.549999  46.700001  39.934162   
3     2005      4   27  46.700001  50.880001  46.180000  48.049999  41.088573   
4     2005      4   28  48.000000  49.349998  47.330002  47.779999  40.857697   
...    ...    ...  ...        ...        ...        ...        ...        ...   
3712  2020      6    1   1.650000   1.650000   1.600000   1.650000   1.650000   
3713  2020      6    2   1.700000   1.700000   1.650000   1.700000   1.700000   
3714  2020      6    3   1.750000   1.750000   1.650000   1.750000   1.750000   
3715  2020      6    4   1.750000   1.800000   1.700000   1.800000   1.800000   
3716  2020      6    5   1.850000   1.950000   1.850000   1.950000   1.950000   

        Volume  
0     33041772  
1     10215112  
2      6801556  
3     18723616  
4      7412076  
...        ...  
3712   2000865  
3713   5358362  
3714   6215851  
3715   4622105  
3716   2019819  

[3717 rows x 9 columns]

In [12]:
scaled_data.columns.values



array(['Year', 'Month', 'Day', 'Open', 'High', 'Low', 'Close',
       'Adj Close', 'Volume'], dtype=object)

In [13]:
cols2=['Year', 'Month', 'Day', 'Open', 'High', 'Low', 'Close','Volume']
x=scaled_data[cols2]
y=scaled_data.iloc[:,7]

In [14]:
x

Year  Month  Day       Open       High        Low      Close    Volume
0     2005      4   22  59.000000  59.000000  48.000000  49.049999  33041772
1     2005      4   25  49.450001  49.849998  47.099998  47.480000  10215112
2     2005      4   26  47.830002  48.130001  46.549999  46.700001   6801556
3     2005      4   27  46.700001  50.880001  46.180000  48.049999  18723616
4     2005      4   28  48.000000  49.349998  47.330002  47.779999   7412076
...    ...    ...  ...        ...        ...        ...        ...       ...
3712  2020      6    1   1.650000   1.650000   1.600000   1.650000   2000865
3713  2020      6    2   1.700000   1.700000   1.650000   1.700000   5358362
3714  2020      6    3   1.750000   1.750000   1.650000   1.750000   6215851
3715  2020      6    4   1.750000   1.800000   1.700000   1.800000   4622105
3716  2020      6    5   1.850000   1.950000   1.850000   1.950000   2019819

[3717 rows x 8 columns]

In [15]:
y

0       41.943699
1       40.601158
2       39.934162
3       41.088573
4       40.857697
          ...    
3712     1.650000
3713     1.700000
3714     1.750000
3715     1.800000
3716     1.950000
Name: Adj Close, Length: 3717, dtype: float64

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x)



StandardScaler()

In [17]:
x_scaled=sc.transform(x)
x_scaled

array([[-1.67903082, -0.72509348,  0.70645545, ...,  0.23525332,
         0.23553417,  9.46353201],
       [-1.67903082, -0.72509348,  1.04853217, ...,  0.21434678,
         0.1998196 ,  2.47764292],
       [-1.67903082, -0.72509348,  1.16255774, ...,  0.2015706 ,
         0.18207608,  1.43295554],
       ...,
       [ 1.7432973 , -0.1410275 , -1.46003043, ..., -0.84143164,
        -0.84045282,  1.25370592],
       [ 1.7432973 , -0.1410275 , -1.34600485, ..., -0.84027016,
        -0.83931541,  0.76595463],
       [ 1.7432973 , -0.1410275 , -1.23197928, ..., -0.83678574,
        -0.83590319, -0.03045103]])

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
y_scaled=sc.fit_transform(y.values.reshape(-1,1))

In [19]:

y_scaled

array([[ 0.15577687],
       [ 0.12203937],
       [ 0.10527803],
       ...,
       [-0.85427445],
       [-0.85301797],
       [-0.84924853]])

In [20]:
from sklearn.model_selection import train_test_split
x_train_val,x_test,y_train_val,y_test=train_test_split(x_scaled,y_scaled,test_size=0.2,random_state=2)
x_train_val

array([[ 0.37436605,  0.44303848,  0.70645545, ..., -0.67766402,
        -0.68121584, -0.43528424],
       [-1.67903082,  1.61117044, -0.77587699, ...,  0.82760427,
         0.8117445 , -0.03163939],
       [ 1.51514209, -1.30915946, -1.34600485, ..., -0.80658746,
        -0.80746801,  0.30758296],
       ...,
       [ 0.60252126,  0.44303848,  0.36437873, ..., -0.81239482,
        -0.81429245, -0.33208025],
       [ 0.60252126,  1.02710446, -0.77587699, ..., -0.78451949,
        -0.78471988, -0.02066477],
       [ 1.28698688, -0.1410275 ,  0.47840431, ..., -0.78684243,
        -0.78130766,  2.15650024]])

In [21]:
x_test

array([[ 1.7432973 , -1.60119245, -1.11795371, ..., -0.83097839,
        -0.83135356,  0.22210913],
       [ 1.7432973 , -1.60119245, -1.46003043, ..., -0.83213986,
        -0.82794134,  2.58107002],
       [-0.31009957, -0.43306049,  0.13632759, ...,  0.23757623,
         0.21961046,  0.04576537],
       ...,
       [-1.45087561,  0.15100549,  0.36437873, ...,  0.77069219,
         0.74964218, -0.44468796],
       [-0.53825478,  0.15100549,  0.47840431, ...,  0.63015395,
         0.60405405, -0.38207782],
       [ 0.37436605, -1.60119245,  0.82048102, ..., -0.69276316,
        -0.69031509, -0.55113904]])

In [22]:
y_train_val

array([[-0.67836729],
       [ 0.73676519],
       [-0.81783653],
       ...,
       [-0.82537541],
       [-0.79270695],
       [-0.78893751]])

In [23]:
y_test

array([[-0.84422261],
       [-0.84045317],
       [ 0.27823341],
       [ 0.5591516 ],
       [ 0.53123434],
       [-0.78265511],
       [ 0.33663184],
       [-0.67082841],
       [-0.78893751],
       [ 0.60064135],
       [ 1.08026138],
       [ 0.55035858],
       [-0.84799205],
       [-0.82788837],
       [ 1.57877874],
       [ 1.21970846],
       [-0.69344506],
       [-0.74747367],
       [-0.71103577],
       [ 2.36139479],
       [-0.76255143],
       [ 0.16114906],
       [-0.26875494],
       [ 0.75758713],
       [-0.77009031],
       [ 0.15503797],
       [ 0.8152712 ],
       [-0.84799205],
       [ 1.04817739],
       [-0.74998663],
       [ 1.77388969],
       [-0.79898934],
       [ 0.20401874],
       [-0.84799205],
       [ 1.19909108],
       [-0.81029766],
       [-0.79396342],
       [-0.69847097],
       [-0.7952199 ],
       [ 0.46559499],
       [-0.74496072],
       [-0.12251005],
       [ 2.29906891],
       [-0.70349688],
       [-0.27629379],
       [ 2

In [24]:
x_train, x_val, y_train, y_val = train_test_split(x_train_val, y_train_val, test_size=0.25, random_state=42)
x_train

array([[-0.76640999, -1.60119245,  0.59242988, ..., -0.15383995,
        -0.16028345, -0.47313261],
       [-0.76640999, -1.30915946,  1.27658331, ..., -0.21539798,
        -0.2217034 , -0.46286494],
       [-0.76640999, -0.1410275 , -1.68808157, ...,  0.85199526,
         0.96119977,  0.27376851],
       ...,
       [ 0.83067647, -1.30915946,  0.25035316, ..., -0.78335801,
        -0.78471988, -0.40307253],
       [ 1.28698688, -1.60119245, -1.574056  , ..., -0.68463286,
        -0.6891777 ,  4.09529497],
       [ 0.83067647,  0.15100549, -1.23197928, ..., -0.7624515 ,
        -0.76424655, -0.17500267]])

In [25]:
y_train

array([[-0.16315526],
       [-0.22586479],
       [ 0.98187593],
       ...,
       [-0.79270695],
       [-0.68716266],
       [-0.77009031]])

In [26]:
x_val

array([[ 0.83067647, -0.72509348,  1.50463446, ..., -0.78219654,
        -0.78358247, -0.28702859],
       [-1.2227204 ,  1.02710446, -1.23197928, ...,  2.54658348,
         2.5114857 , -0.25304888],
       [-1.45087561,  1.61117044, -0.20574913, ...,  1.12029529,
         1.11474972, -0.34785298],
       ...,
       [ 1.05883167, -0.72509348, -1.00392814, ..., -0.7543212 ,
        -0.7562847 ,  0.3808938 ],
       [-0.31009957, -1.60119245,  0.13632759, ...,  0.38740619,
         0.36861084, -0.55706063],
       [-1.2227204 ,  0.44303848, -1.46003043, ...,  2.40836833,
         2.35406827, -0.39520483]])

In [27]:
y_val

array([[-0.79145046],
       [ 2.51284645],
       [ 1.0827095 ],
       [-0.81783653],
       [ 2.08731711],
       [ 0.17481953],
       [ 0.81289479],
       [-0.80401526],
       [ 2.68645177],
       [ 0.53892783],
       [ 1.06362514],
       [-0.13528431],
       [ 1.25013365],
       [-0.43209729],
       [ 2.31724027],
       [-0.44968798],
       [-0.67836729],
       [ 1.09927422],
       [-0.77511622],
       [-0.76380791],
       [ 1.82307696],
       [-0.10276813],
       [-0.80904118],
       [ 2.60694209],
       [-0.74496072],
       [-0.79145046],
       [-0.77511622],
       [-0.59418314],
       [ 0.10303822],
       [-0.84547909],
       [ 0.96073457],
       [-0.84799205],
       [ 0.15292019],
       [ 0.63227392],
       [-0.78642455],
       [-0.7022404 ],
       [-0.77134678],
       [-0.78265511],
       [-0.73993479],
       [-0.64946827],
       [-0.28044542],
       [-0.22100867],
       [-0.84296613],
       [-0.77260327],
       [ 2.38472985],
       [ 2

In [28]:
x_train.shape

(2229, 8)

In [29]:
x_val.shape

(744, 8)

In [30]:
x_test.shape

(744, 8)

In [31]:
np.savez('Stock Prediction Train',inputs=x_train,targets=y_train)
np.savez('Stock Prediction Validate',inputs=x_val,targets=y_val)
np.savez('Stock Prediction Test',inputs=x_test,targets=y_test)

In [32]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [33]:
results=lr.score(x_test,y_test)

In [34]:
results

0.9987356614482827

In [35]:
y_pred=lr.predict(x_test)
y_pred

array([[-0.8247882 ],
       [-0.82959606],
       [ 0.21749856],
       [ 0.622235  ],
       [ 0.59271876],
       [-0.77771977],
       [ 0.26035609],
       [-0.67311637],
       [-0.78139118],
       [ 0.51949577],
       [ 1.0205925 ],
       [ 0.61154941],
       [-0.81993476],
       [-0.82401788],
       [ 1.55339987],
       [ 1.30706625],
       [-0.69856933],
       [-0.75003831],
       [-0.71148321],
       [ 2.37777886],
       [-0.75558269],
       [ 0.21509425],
       [-0.30928306],
       [ 0.66775592],
       [-0.75846344],
       [ 0.15026249],
       [ 0.76041717],
       [-0.8228225 ],
       [ 0.98324799],
       [-0.7367636 ],
       [ 1.77918185],
       [-0.79387675],
       [ 0.14451579],
       [-0.82153147],
       [ 1.13539125],
       [-0.7921445 ],
       [-0.77839436],
       [-0.70160406],
       [-0.78468988],
       [ 0.39154131],
       [-0.73818969],
       [-0.13239883],
       [ 2.34310153],
       [-0.70521046],
       [-0.31630065],
       [ 2

In [36]:
from sklearn.metrics import r2_score,mean_squared_error
r2_score(y_test,y_pred)


0.9987356614482827

In [37]:
y_pred_unscaled=sc.inverse_transform(y_pred)
y_pred_unscaled

array([[  2.92336761],
       [  2.73204485],
       [ 44.39983441],
       [ 60.50580274],
       [ 59.33124175],
       [  4.79639538],
       [ 46.10529488],
       [  8.95895362],
       [  4.65029631],
       [ 56.41742693],
       [ 76.35792938],
       [ 60.08058354],
       [  3.11650367],
       [  2.95402137],
       [ 97.56031662],
       [ 87.75778571],
       [  7.94608564],
       [  5.89794345],
       [  7.43219429],
       [130.36542286],
       [  5.67731209],
       [ 44.30415809],
       [ 23.4372343 ],
       [ 62.31724976],
       [  5.56267628],
       [ 41.72426133],
       [ 66.00458523],
       [  3.00158996],
       [ 74.87185277],
       [  6.42619349],
       [106.54502138],
       [  4.15344881],
       [ 41.49557845],
       [  3.05296485],
       [ 80.92619886],
       [  4.22238158],
       [  4.76955106],
       [  7.82532238],
       [  4.51902862],
       [ 51.32564294],
       [  6.36944434],
       [ 30.47611567],
       [128.98548302],
       [  7

In [38]:
y_pred_unscaled.shape

(744, 1)

In [39]:
data = np.load('data.npz')
data

NpzFile 'data.npz' with keys: var1, var2

In [40]:
test_targets=data['var1']
pred_targets=data['var2']

In [41]:
df1 = pd.DataFrame(test_targets)
df2 = pd.DataFrame(pred_targets)

In [44]:
score_data=pd.concat([df1,df2],axis=1)

In [45]:
score_data

0         0
0   -0.844223 -0.807927
1   -0.840453 -0.825755
2    0.278233  0.272881
3    0.559152  0.573707
4    0.531234  0.545615
..        ...       ...
739 -0.415763 -0.457279
740  0.528860  0.461462
741  0.720173  0.745218
742  0.689456  0.648461
743 -0.688419 -0.692195

[744 rows x 2 columns]

In [46]:
score_data.columns.values

array([0, 0], dtype=int64)

In [47]:
cols=['Test targets','Predicted targets']
score_data.columns=cols

In [48]:
score_data

Test targets  Predicted targets
0       -0.844223          -0.807927
1       -0.840453          -0.825755
2        0.278233           0.272881
3        0.559152           0.573707
4        0.531234           0.545615
..            ...                ...
739     -0.415763          -0.457279
740      0.528860           0.461462
741      0.720173           0.745218
742      0.689456           0.648461
743     -0.688419          -0.692195

[744 rows x 2 columns]

In [49]:
from sklearn.metrics import r2_score
r2_score(test_targets,pred_targets)

0.9986184979003969

In [51]:
score_data.to_csv('R2_Score data',index=False)